# Generated by Django 4.2.1 on 2023-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_update_post_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
