# Generated by Django 4.2.1 on 2023-06-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titel',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
